version: '3.1'
services:
  app:
    container_name: profile_back
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spark