version: '3.1'
services:

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spark

  profile_back:
    container_name: profile_back
    image: madsum/profileback_app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  profile_front:
    container_name: profile_front
    image: madsum/madsum/profile_front
    build: ./../Profile_Front/
    ports:
      - "3000:3000"
    depends_on:
      - profile_back




